# Generated by Django 6.0.7 on 2026-07-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_gst_product_product_code_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, editable=False, max_length=10, unique=True),
        ),
    ]
